version: '3'

services:
  sinergiarh-challenge:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://sinergiarh-challenge:3306/b7v2h0wyhihgvv2hla9q
      DB_USER_NAME: u4xbhafwsx3z5lg0
      DB_PASSWORD: BEbxLe6x7uSuhiTzZiPf
    restart: always
    depends_on:
      sinergiarh-db:
          condition: service_healthy
  sinergiarh-db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: sinergiarh-challenge
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10