version: '3'

services:
  sinergiarh-challenge:
    build: .
    mem_limit: 512m
    ports:
      - "10000:10000"
    environment:
      DB_URL: jdbc:mysql://sinergiarh-db:3306/sinergiarh-challenge
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      sinergiarh-db:
          condition: service_healthy
  sinergiarh-db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: sinergiarh-challenge
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10